name: Code Review

on:
  pull_request:
    branches:
      - qa
      - master

jobs:
  code-review:
    name: Code Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: List
        run: ls -la
      - name: Check style guide
        uses: wemake-services/wemake-python-styleguide
        with:
          reporter: github-pr-review
          path: src
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
